services:
  auctionservice:
    build:
      context: .
      dockerfile: Carsties/Dockerfile
    image: auctionservice:dev
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_USER: postgres
      POSTGRES_DB: auctions
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auctions"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    ports:
    - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/data
volumes:
  pgdata:
  mongodata:
